name: westcompdoc.com
favicon: null
layout_spectrum: 0.738155075116083
typography_spectrum: 0.3257395608816296
title: Computer Repair / IT / Web development / Photography / Videography / Graphic Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22bd17'
    - '#fee800'
    - '#040406'
    - '#004000'
    - '#9f9a00'
  brandStrength: 0.25859985896386206
  lightness: 0.31866419571451843
  saturation: 0.75
  rhythmicContrast: 0.9917917125858366
purpose: []
